services:
    compass_api:
        container_name: compass_api
        build: .
        image: compass_api
        env_file:
            - ".env"
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_DB=compass_db
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=pwd
        depends_on:
            - db

    db:
        container_name: db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=compass_db
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=pwd