services:
    compass_api:
        container_name: compass_api
        build: .
        image: compass_api
        ports:
            - "3000:3000"
        environment:
            - PG_DB=${PG_DB}
            - PG_USER=${PG_USER}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_HOST=${PG_HOST}
        depends_on:
            - compass_pg_db

    compass_pg_db:
        container_name: compass_pg_db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${PG_DB}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        volumes:
            - compass_pg_db_data:/var/lib/postgresql/data

volumes:
    compass_pg_db_data: {}